version: '3'

services:
  mariadb:
    image: mariadb:10.2
    container_name: mariadb

    # Uncomment if you want access to DB access from Host mariadb://root:1234@127.0.0.1?statusColor=F8F8F8&enviroment=local&name=localhost&tLSMode=0&usePrivateKey=false&safeModeLevel=0&advancedSafeModeLevel=0
    ports:
       - "3306:3306"
#    networks:
#      - mariadb_default
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    volumes:
      - ./datadir:/var/lib/mysql
    restart: always
#    deploy:
#      mode: replicated
#      replicas: 1
#      restart_policy:
#        condition: on-failure
#        delay: 10s
#        max_attempts: 3
#        window: 120s

  jasperserver:
    # build: .
    image: thoonly/jasperserver-ce-711
    container_name: jasperserver
    ports:
      - "8890:8080"
#    networks:
#      - mariadb_default
    environment:
      - DB_TYPE=mysql
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=mysql
    volumes:
      # Relative path on the host/volume on container
      - ./jasperserver-import:/jasperserver-import
    restart: always
    depends_on:
      - mariadb
#    deploy:
#      mode: replicated
#      replicas: 1
#      restart_policy:
#        condition: on-failure
#        delay: 10s
#        max_attempts: 3
#        window: 120s
networks:
 mariadb_default:
   external: true
